sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: '/%sylius_admin.path_name%'

sylius_paypal_admin:
    resource: "@SyliusPayPalPlugin/Resources/config/admin_routing.yml"
    prefix: '/%sylius_admin.path_name%'

websnacks_sylius_admin_notification_plugin.admin.notifications_list:
    path: /admin/notifications/list
    methods: [GET]
    defaults:
        _controller: App\Controller\Admin\Notification\NotificationList

websnacks_sylius_admin_notification_plugin.admin.mark_as_read:
    path: /admin/notifications/read
    methods: [POST]
    defaults:
        _controller: App\Controller\Admin\Notification\ReadNotification

app_admin_product_additional_options:
    path: /admin/products/{id}/additionals
    methods: [GET, PUT, PATCH]
    defaults:
        _controller: sylius.controller.product:updateAction
        _sylius:
            section: admin
            form: App\Form\Type\ProductAdditionalOptionsType
            template: "Admin/Product/additionalOptions.html.twig"
            redirect:
                route: app_admin_product_additional_options
                parameters:
                    id: $id
